#!/bin/bash

# Update sources
sudo apt-get update

# Install basics
sudo apt-get install build-essential dkms net-tools binutils cpp gcc make psmisc linux-headers-$(uname -r)

# Install git & python
sudo apt-get install python3 python3-dev python3-pip git meld

# For VMWare, comment out
# sudo apt-get install open-vm-tools open-vm-tools-desktop open-vm-tools-dev

# Install pipenv
sudo pip3 install pipenv

# Set up pipenv
pipenv --three

# Install Python dependencies
pipenv install

# Start pipenv
pipenv shell
