##################################
#
# Virtualenvwrapper
#
##################################
export WORKON_HOME="~/.python-env"
if [ -f "/usr/local/bin/virtualenvwrapper.sh" ]; then
    source "/usr/local/bin/virtualenvwrapper.sh"
fi

