####################################
#
# Zsh
#
####################################
# Zsh prompt
ZSH_THEME="bureau"

# terminal to support 256 color schemes
export TERM="xterm-256color"

# prompts for 'rm *' completions
setopt RM_STAR_WAIT

# allow bash style comments
setopt interactivecomments

# spelling corrector
setopt CORRECT

# source oh-my-zsh file
ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

